# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload to Flathub

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2
    - name: Build and publish
      env:
        PASSWORD_DEPLOYEMENT: ${{ secrets.PASSWORD_DEPLOYEMENT }}
      run: |
        ./deploy.sh $(cat src/version.py | cut -d " " -f 3)
