name: Run Python Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install dependency
        run: |
          sudo apt-get install gcc xvfb gir1.2-gtk-3.0 python3-gi python3-gi-cairo libgirepository1.0-dev 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install coverage codecov pytest-cov

      - name: Run tests with pytest nd flake8
        run: |
          pytest tests --cov=src
          codecov 

      - name: Run flake8
        run: |
          flake8
